[project]
name = "comfymath-ng"
version = "0.1.3"
description = "A maintained fork of ComfyMath providing math nodes for ComfyUI"
authors = [
    "Evan Spearman <evan@spearman.mb.ca>",
    "Raphael Stoeckli <https://github.com/rabanti-github>",
]
license = {file = "LICENSE"}
readme =  {file = "README.md"}

[tool.comfy]
PublisherId = "rabanti"
DisplayName = "ComfyMath-NG"

[project.urls]
Repository = "https://github.com/rabanti-github/ComfyMath.git"
Issues = "https://github.com/rabanti-github/ComfyMath/issues"
Changelog = "https://raw.githubusercontent.com/rabanti-github/ComfyMath/refs/heads/main/CHANGELOG.md"

[tool.setuptools.dynamic]
dependencies = {file = ["requirements.txt"]}

[tool.poetry.dependencies]
python = "^3.10"
numpy = "^1.25.1"

[tool.poetry.group.dev.dependencies]
mypy = "^1.4.1"
black = "^23.7.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"