[project]
name = "comfymath-ng"
version = "0.1.6"
description = "A maintained fork of ComfyMath, provides Math Nodes for ComfyUI. Boolean Logic, Integer Arithmetic and Randomization, Floating Point Arithmetic and Functions, Vec2, Vec3, and Vec4 Arithmetic and Functions"
authors = [
    {name = "Evan Spearman", email = "evan@spearman.mb.ca"},
    {name = "Raphael Stoeckli"},
]
license = {file = "LICENSE"}
readme = "README.md"

[tool.comfy]
PublisherId = "rabanti"
DisplayName = "ComfyMath-NG"

[project.urls]
Repository = "https://github.com/rabanti-github/ComfyMath.git"
Issues = "https://github.com/rabanti-github/ComfyMath/issues"
Changelog = "https://raw.githubusercontent.com/rabanti-github/ComfyMath/refs/heads/main/CHANGELOG.md"

[tool.setuptools.dynamic]
dependencies = {file = ["requirements.txt"]}

[tool.poetry.dependencies]
python = "^3.10"
numpy = "^1.25.1"

[tool.poetry.group.dev.dependencies]
mypy = "^1.4.1"
black = "^23.7.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
