[tool.poetry]
name = "comfymath"
version = "0.1.2"
description = "Math nodes for ComfyUI, updated fork"
authors = [
    "Evan Spearman <evan@spearman.mb.ca>",
    "Raphael Stoeckli <https://github.com/rabanti-github>",
]
license = "Apache-2.0"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
numpy = "^1.25.1"

[tool.poetry.group.dev.dependencies]
mypy = "^1.4.1"
black = "^23.7.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
